// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package qualia

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QualiaServiceClient is the client API for QualiaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QualiaServiceClient interface {
	ReceiveNewTxn(ctx context.Context, in *Txn, opts ...grpc.CallOption) (*TxnResponse, error)
}

type qualiaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQualiaServiceClient(cc grpc.ClientConnInterface) QualiaServiceClient {
	return &qualiaServiceClient{cc}
}

func (c *qualiaServiceClient) ReceiveNewTxn(ctx context.Context, in *Txn, opts ...grpc.CallOption) (*TxnResponse, error) {
	out := new(TxnResponse)
	err := c.cc.Invoke(ctx, "/qualia.QualiaService/ReceiveNewTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QualiaServiceServer is the server API for QualiaService service.
// All implementations must embed UnimplementedQualiaServiceServer
// for forward compatibility
type QualiaServiceServer interface {
	ReceiveNewTxn(context.Context, *Txn) (*TxnResponse, error)
	mustEmbedUnimplementedQualiaServiceServer()
}

// UnimplementedQualiaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQualiaServiceServer struct {
}

func (UnimplementedQualiaServiceServer) ReceiveNewTxn(context.Context, *Txn) (*TxnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveNewTxn not implemented")
}
func (UnimplementedQualiaServiceServer) mustEmbedUnimplementedQualiaServiceServer() {}

// UnsafeQualiaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QualiaServiceServer will
// result in compilation errors.
type UnsafeQualiaServiceServer interface {
	mustEmbedUnimplementedQualiaServiceServer()
}

func RegisterQualiaServiceServer(s grpc.ServiceRegistrar, srv QualiaServiceServer) {
	s.RegisterService(&QualiaService_ServiceDesc, srv)
}

func _QualiaService_ReceiveNewTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Txn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualiaServiceServer).ReceiveNewTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qualia.QualiaService/ReceiveNewTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualiaServiceServer).ReceiveNewTxn(ctx, req.(*Txn))
	}
	return interceptor(ctx, in, info, handler)
}

// QualiaService_ServiceDesc is the grpc.ServiceDesc for QualiaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QualiaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qualia.QualiaService",
	HandlerType: (*QualiaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveNewTxn",
			Handler:    _QualiaService_ReceiveNewTxn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qualia/txn.proto",
}
